const labels: Record<string, string> = {
    nezha: "Kulin",
    Username: "用户名",
    Password: "密码",
    InvalidUsernameOrPassword: "用户名或密码错误",
    NetworkError: "网络错误",
    LoginFirst: "请先登录",
    CurrentTime: "当前时间",
    Login: "登录",
    Server: "服务器",
    Service: "延迟监控",
    Task: "任务",
    Notification: "通知",
    NATT: "内网穿透",
    Group: "分组",
    Profile: "个人信息",
    Settings: "系统设置",
    BackToHome: "返回前台",
    Logout: "登出",
    NavigateTo: "导航至",
    SelectAPageToNavigateTo: "选择一个页面跳转",
    Close: "关闭",
    Error: "错误",
    Name: "名称",
    Sort: "排序",
    Version: "版本",
    Unknown: "未知",
    Enable: "启用",
    InstallCommands: "安装命令",
    Config: "配置",
    Note: "备注",
    Success: "成功",
    Done: "完成",
    Offline: "离线",
    Failure: "失败",
    Loading: "加载中",
    NoResults: "没有内容",
    Actions: "操作",
    EditServer: "编辑服务器",
    SeparateWithComma: "（以英文逗号分隔）",
    Public: "公开",
    Private: "私有",
    Submit: "提交",
    Target: "目标",
    Coverage: "覆盖范围",
    CoverAll: "覆盖全部",
    IgnoreAll: "忽略全部",
    OnAlert: "告警服务器",
    SpecificServers: "特定服务器",
    Type: "类型",
    Interval: "间隔",
    NotifierGroupID: "通知渠道ID",
    Trigger: "触发",
    TasksToTriggerOnAlert: "告警时要触发的任务",
    TasksToTriggerAfterRecovery: "恢复后要触发的任务",
    Add: "添加",
    Delete: "删除",
    AdvancedJSON: "高级 JSON",
    Save: "保存",
    Confirm: "确认",
    ConfirmDeletion: "确认删除？",
    Services: "延迟监控",
    EnableFailureNotification: "启用失败通知",
    MaximumLatency: "最大延迟时间（毫秒）",
    MinimumLatency: "最小延迟时间（毫秒）",
    EnableLatencyNotification: "启用延迟通知",
    EnableTriggerTask: "启用触发任务",
    CronExpression: "Cron表达式",
    Command: "命令",
    NotifierGroup: "通知渠道",
    SendSuccessNotification: "发送成功通知",
    LastExecution: "最后执行",
    Result: "结果",
    Scheduled: "计划任务",
    AlertRule: "警报规则",
    Notifier: "通知",
    VerifyTLS: "验证 TLS",
    TriggerMode: "触发模式",
    Rules: "规则",
    RequestMethod: "请求方式",
    RequestHeader: "请求头",
    DoNotSendTestMessage: "不发送测试消息",
    Always: "总是",
    Once: "仅一次",
    Provider: "提供商",
    Domains: "域名",
    MaximumRetryAttempts: "最大重试次数",
    Refresh: "刷新",
    CopyPath: "复制路径",
    Goto: "前往",
    UpdateProfile: "更新个人资料",
    NewUsername: "新用户名",
    OriginalPassword: "原始密码",
    NewPassword: "新密码",
    EditDDNS: "编辑DDNS",
    CreateDDNS: "创建DDNS",
    Credential: "凭据",
    RequestType: "请求类型",
    RequestBody: "请求体",
    Downloading: "下载中",
    Uploading: "上传中",
    EditNAT: "编辑内网穿透配置",
    CreateNAT: "创建内网穿透配置",
    LocalService: "本地服务",
    BindHostname: "绑定域名",
    EditServerGroup: "编辑服务器分组",
    CreateServerGroup: "创建服务器分组",
    EditService: "编辑服务",
    CreateService: "创建服务",
    EditTask: "编辑任务",
    CreateTask: "创建任务",
    EditNotifier: "编辑通知",
    CreateNotifier: "创建通知",
    EditAlertRule: "编辑报警规则",
    CreateAlertRule: "创建报警规则",
    EditNotifierGroup: "编辑通知渠道",
    CreateNotifierGroup: "创建通知渠道",
    User: "用户",
    SiteName: "站点名称",
    AvatarURL: "头像链接",
    CustomCodes: "自定义代码（样式和脚本）",
    CustomCodesDashboard: "仪表板的自定义代码",
    DashboardOriginalHost: "Agent对接地址【域名/IP:端口】",
    DashboardHost: "面板 OAuth2 回调域名【域名/IP:端口】",
    DashboardHostHint:
        "用于生成 OAuth2 回调地址的面板对外域名。当面板访问域名与 Agent 对接地址不同时设置此项。留空则信任请求 Host，不做强制重写。",
    ReservedHosts: "保留 Host（逗号分隔；反代/公网域名，成员不可注册为 NAT 域名）",
    ReservedHostsHint:
        "反代部署下面板看不到自身的对外域名，无法自动保护。请在此列出所有公网入口域名，否则成员可将其注册为 NAT 域名抢占面板路由。",
    ConfigTLS: "Agent 使用 TLS 连接",
    CustomPublicDNSNameserversforDDNS: "DDNS 的自定义公共 DNS 名称服务器",
    WebRealIPHeader: "前端真实IP请求头",
    AgentRealIPHeader: "Agent真实IP请求头",
    UseDirectConnectingIP: "使用直连 IP",
    IPChangeNotification: "IP变更通知",
    FullIPNotification: "在通知消息中显示完整的 IP 地址",
    EnableMCP: "启用 MCP 接入（默认关闭；启用前请确认已审阅 API 令牌 scope 与服务器白名单）",
    LoginFailed: "登录失败",
    BruteForceAttackingToken: "暴力攻击令牌",
    BruteForceAttackingAgentSecret: "暴力攻击代理秘密",
    NewUser: "新用户",
    Count: "计数",
    LastBlockReason: "最后封禁原因",
    LastBlockTime: "最后封禁时间",
    Theme: "主题",
    Author: "作者",
    Repository: "仓库",
    Community: "社区",
    Official: "官方",
    CommunityThemeWarning: "正在使用社区主题",
    CommunityThemeDescription: "社区主题未经官方审计，需自行甄别风险",
    Cancel: "取消",
    PushSuccessful: "推送成功的通知",
    GrpcAuthFailed: "gRPC 认证失败",
    APITokenInvalid: "API 令牌无效",
    UserInvalid: "用户无效",
    BlockByUser: "被管理员封禁",
    BlockIdentifier: "封禁标识",
    UserId: "用户 ID",
    ConnectedAt: "连接时间",
    Total: "总数",
    ConfirmBlock: "确认封禁",
    EmptyText: "空文本",
    EmptyNote: "您没有任何备注。",
    EditServerConfig: "编辑服务器配置",
    OverrideDDNSDomains: "强制指定 DDNS 域名（每个配置）",
    Value: "值",
    Preview: "预览",
    Option: "选项",
    Search: "搜索...",
    Format: "格式化",
    Formatted: "已格式化",
    Copy: "复制",
    Paste: "粘贴",
    CopiedToClipboard: "已复制到剪贴板",
    ClipboardWriteFailed: "无法写入剪贴板",
    PastedFromClipboard: "已从剪贴板粘贴",
    ClipboardReadFailed: "无法读取剪贴板",
    FormatMetricUnits: "格式化数据单位",
    Status: "状态",
    CreatedAt: "创建时间",
    Servers: "服务器",
    ToUser: "目标用户",
    Move: "转移",
    NameRequired: "名称必填。",
    Copied: "已复制到剪贴板",
    "theme.light": "浅色",
    "theme.dark": "深色",
    "theme.system": "跟随系统",
    Scopes: "权限",
    "PublicNote.Label": "公开备注",
    "PublicNote.CustomFields": "表单填写",
    "PublicNote.RawText": "原始文本",
    "PublicNote.StartDate": "开始日期",
    "PublicNote.EndDate": "结束日期",
    "PublicNote.ClearDate": "清除日期",
    "PublicNote.SetNoExpiry": "设为永久",
    "PublicNote.CancelNoExpiry": "取消永久",
    "PublicNote.NoExpiry": "永久",
    "PublicNote.AutoRenewal": "自动续费",
    "PublicNote.Disabled": "关闭",
    "PublicNote.Enabled": "开启",
    "PublicNote.Cycle": "周期",
    "PublicNote.Clear": "清除",
    "PublicNote.Day": "日",
    "PublicNote.Week": "周",
    "PublicNote.Month": "月",
    "PublicNote.Year": "年",
    "Validation.MustBeBillingCycle": "账单周期无效",
    "PublicNote.FiveYears": "五年",
    "PublicNote.ThreeYears": "三年",
    "PublicNote.TwoYears": "两年",
    "PublicNote.HalfYear": "半年",
    "PublicNote.Quarter": "季",
    "PublicNote.Amount": "金额",
    "PublicNote.Free": "免费",
    "PublicNote.PayAsYouGo": "按量付费",
    "PublicNote.RenewalNotify": "续费通知",
    "PublicNote.RenewalNotifyOff": "关闭",
    "PublicNote.RenewalNotifyToday": "当天",
    "PublicNote.RenewalNotifyOneDay": "提前 1 天",
    "PublicNote.RenewalNotifyThreeDays": "提前 3 天",
    "PublicNote.RenewalNotifySevenDays": "提前 7 天",
    "Validation.MustBe0Or1": "必须是 0 或 1",
    "Validation.MustBeRenewalNotifyDays": "续费通知只能选择当天、提前 1/3/7 天",
    "Validation.MustBeDayWeekMonthYear": "必须是 Day、Week、Month 或 Year",
    "Validation.InvalidDate": "日期无效",
    "Validation.InvalidForm": "表单内容有误",
    "Results.ErrorFetchingResource": "获取或保存资源失败：{{error}}",
    "Results.UnExpectedError": "发生未知错误",
}

export function t(key: string, fallback?: unknown): string {
    return labels[key] || (typeof fallback === "string" ? fallback : key)
}
