name: kulin-dashboard

services:
  dashboard:
    image: ghcr.io/shuijiao1/kulin-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kulin-dashboard
    restart: unless-stopped
    ports:
      - "8031:8008"
    volumes:
      - ./data:/dashboard/data
